spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ilya
    password: bebra
    url: jdbc:postgresql://localhost:5432/cloud_storage

  jpa:
    hibernate:
      ddl-auto: validate

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: -1 # No file size limit
      max-request-size: -1  # No limit on request size

  session:
    timeout: 1D