spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ilya
    password: bebra
    url: jdbc:postgresql://localhost:5432/cloud_storage

  jpa:
    hibernate:
      ddl-auto: validate