spring:
  data:
    redis:
      host: redis

  datasource:
    username: ilya
    password: bebra
    url: jdbc:postgresql://postgres:5432/cloud-storage

  servlet:
    multipart:
      max-file-size: 20MB # No file size limit
      max-request-size: 20MB  # No limit on request size

  session:
    timeout: 1D

minio:
  endpoint: http://minio:9000
  username: ilya
  password: bebrabebra