spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true

server:
  tomcat:
    max-swallow-size: -1