spring:
  datasource:
    username: ilya
    password: bebra
    url: jdbc:postgresql://localhost:5432/cloud_storage

  servlet:
    multipart:
      max-file-size: 1KB # No file size limit
      max-request-size: 1KB  # No limit on request size

  session:
    timeout: -1 # No timeout

minio:
  endpoint: localhost
  port: 9000
  username: ilya
  password: bebrabebra