spring:
  data:
    redis:
      host: redis

  datasource:
    username: ilya
    password: bebra
    url: jdbc:postgresql://postgres:5432/cloud-storage

  servlet:
    multipart:
      max-file-size: -1 # No file size limit
      max-request-size: -1  # No limit on request size

minio:
  endpoint: http://minio:9000
  username: ilya
  password: bebrabebra