spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/cloud-file-storage

  data:
    redis:
      host: redis
      password: ${REDIS_PASSWORD}

  session:
    timeout: 7D

minio:
  endpoint: http://minio:9000
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}