spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  session:
    timeout: 7d