version: "3.9"

# testing application container integration locally
services:
  cloud-file-storage:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - LOGS_FOLDER_PATH=${LOGS_FOLDER_PATH}
    volumes:
      - ~/logs:${LOGS_FOLDER_PATH}
    restart: always

  postgres:
    image: postgres:15
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: cloud-file-storage
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: bebra
    restart: always

  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - ~/data/redis:/var/lib/redis
    restart: always

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
    command: server /data --console-address ":9001"
    volumes:
      - ~/data/minio:/data
    environment:
      MINIO_ROOT_USER: ilya
      MINIO_ROOT_PASSWORD: bebrabebra
    restart: always