CREATE TABLE Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL CHECK ( char_length(username) > 2 ),
    password VARCHAR(100) NOT NULL CHECK ( char_length(password) > 5 )
);